name: receipt-app

services:
  api:
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n12112798-kr-m5:api-prod-v3.0.4
    ports:
      - "3000:3000" # Direct external API access
    environment:
      - AWS_REGION=ap-southeast-2
    restart: unless-stopped