/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as AppReceiptReceiptIdRouteImport } from './routes/app/receipt/$receiptId'
import { Route as authSignupConfirmationRouteImport } from './routes/(auth)/signup/confirmation'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/(auth)/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReceiptReceiptIdRoute = AppReceiptReceiptIdRouteImport.update({
  id: '/receipt/$receiptId',
  path: '/receipt/$receiptId',
  getParentRoute: () => AppRouteRoute,
} as any)
const authSignupConfirmationRoute = authSignupConfirmationRouteImport.update({
  id: '/(auth)/signup/confirmation',
  path: '/signup/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/': typeof authIndexRoute
  '/app/': typeof AppIndexRoute
  '/signup/confirmation': typeof authSignupConfirmationRoute
  '/app/receipt/$receiptId': typeof AppReceiptReceiptIdRoute
  '/signup': typeof authSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authIndexRoute
  '/app': typeof AppIndexRoute
  '/signup/confirmation': typeof authSignupConfirmationRoute
  '/app/receipt/$receiptId': typeof AppReceiptReceiptIdRoute
  '/signup': typeof authSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/': typeof authIndexRoute
  '/app/': typeof AppIndexRoute
  '/(auth)/signup/confirmation': typeof authSignupConfirmationRoute
  '/app/receipt/$receiptId': typeof AppReceiptReceiptIdRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/'
    | '/app/'
    | '/signup/confirmation'
    | '/app/receipt/$receiptId'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/signup/confirmation'
    | '/app/receipt/$receiptId'
    | '/signup'
  id:
    | '__root__'
    | '/app'
    | '/(auth)/'
    | '/app/'
    | '/(auth)/signup/confirmation'
    | '/app/receipt/$receiptId'
    | '/(auth)/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authIndexRoute: typeof authIndexRoute
  authSignupConfirmationRoute: typeof authSignupConfirmationRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/receipt/$receiptId': {
      id: '/app/receipt/$receiptId'
      path: '/receipt/$receiptId'
      fullPath: '/app/receipt/$receiptId'
      preLoaderRoute: typeof AppReceiptReceiptIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/signup/confirmation': {
      id: '/(auth)/signup/confirmation'
      path: '/signup/confirmation'
      fullPath: '/signup/confirmation'
      preLoaderRoute: typeof authSignupConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppReceiptReceiptIdRoute: typeof AppReceiptReceiptIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppReceiptReceiptIdRoute: AppReceiptReceiptIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authIndexRoute: authIndexRoute,
  authSignupConfirmationRoute: authSignupConfirmationRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
